name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # 1. 소스 코드 체크아웃
      - uses: actions/checkout@v3

      # 2. 빌드 날짜 캐시
      - name: Get Date
        id: get-date
        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_ENV

      # 3. Buildozer 글로벌 디렉토리 캐시
      - name: Cache Buildozer global directory
        uses: actions/cache
