name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # 1. 소스 코드 체크아웃
      - uses: actions/checkout@v3

      # 2. 빌드 날짜 캐시
      - name: Get Date
        id: get-date
        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_ENV

      # 3. Buildozer 글로벌 디렉토리 캐시
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} 
          restore-keys: |
            buildozer-global-

      # 4. Buildozer 디렉토리 캐시
      - name: Cache Buildozer directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.date }}-
            ${{ runner.os }}-

      # 5. Buildozer 및 필수 파이썬 모듈 설치
      - name: Install Buildozer and dependencies
        run: |
          pip install buildozer
          pip install build toml appdirs
          pip install Cython

      # 6. python-for-android 다운로드 (필수)
      - name: Download python-for-android
        run: |
          git clone https://github.com/kivy/python-for-android.git /home/runner/work/project1/project1/.buildozer/android/platform/python-for-android

      # 7. Android NDK 설치
      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r25b
          export PATH=$PATH:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin

      # 8. Android SDK 설치 및 라이선스 자동 수락
      - name: Install Android SDK and accept licenses
        run: |
          sudo apt-get install -y android-sdk
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools
          yes | sdkmanager --licenses

      # 9. Android SDK Build-Tools 설치
      - name: Install Build Tools
        run: sdkmanager "build-tools;35.0.0"

      # 10. pip 최신 버전으로 업그레이드
      - name: Upgrade pip
        run: pip install --upgrade pip

      # 11. Buildozer를 사용해 클린 빌드 및 APK 빌드
      - name: Clean and Build with Buildozer
        run: |
          buildozer android clean
          buildozer android debug

      # 12. 빌드된 APK 업로드
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: ./bin/*.apk
